### ISSUE TITLE
I can send GET to UserViewSet which give me data of all user in database

### ISSUE THREAD

**Issue by Sosokker** [PlanMeProject/PlanMeBackEnd#102]
![image](https://github.com/PlanMeProject/PlanMeBackEnd/assets/22256420/bd10f2c0-a6d0-439b-b6c9-d2f64bab6cd7)

**Comment by Sosokker** [comment]
[This API link is the link I retrieve data from](https://planme-3366bb9023b7.herokuapp.com/api/users/)

**Comment by Jwizzed** [comment]
Thank you for your observation, Fixed.
